apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-vault-plugin-credentials
  namespace: argo-cd
data:
  VAULT_ADDR: "https://vault.svc.gbif.no"
  AVP_TYPE: "vault"
  AVP_AUTH_TYPE: "k8s"
  AVP_K8S_ROLE: "argocd"
  AVP_MOUNT_PATH: "kubernetes"