apiVersion: networking.digitalocean.com/v1
kind: StaticRoute
metadata:
  name: public-egress
spec:
  destinations:
    - "2a02:d140:c013:1935::5/128"  # The biofokus database
    - 129.240.118.168/32  # The MUSIT database
  gateway: 10.110.0.2
