apiVersion: v2
appVersion: 3.4.7
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 2.31.3
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 12.12.10
description: Prefect server application bundle
home: https://github.com/PrefectHQ
maintainers:
- email: jamie@prefect.io
  name: jamiezieziula
- email: jimi@prefect.io
  name: jimid27
- email: edward@prefect.io
  name: parkedwards
- email: mitchell@prefect.io
  name: mitchnielsen
name: prefect-server
sources:
- https://github.com/PrefectHQ/prefect-helm
type: application
version: 2025.6.26211534
