apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatipt.fullname" . }}-frontend
  labels:
    {{- include "chatipt.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontEnd.service.type }}
  ports:
    - port: {{ .Values.frontEnd.service.port }}
      targetPort: {{ .Values.frontEnd.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "chatipt.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
