containerImageTag: 3.2.3
replicas: 1

sharedPvcName: 573890b9-3346-4027-ab0c-22eec6dfd665
pvcSubPath: null

resources:
  limits:
    memory: 1536Mi
    cpu: "1"
  requests:
    memory: 768Mi
    cpu: "0.5"

ingressClassName: nginx
hostName: null
